# To use:
#   $ conda env create -f environment.yml
#   $ conda activate demo
name: machinelearnear-asr-spanish
dependencies:
  - python=3.9
  - pip
  - nb_conda_kernels
  - ipykernel
  - gh
  - librosa
  - ffmpeg
  - pip:
    - torch
    - transformers
    - torchaudio
    - pyctcdecode
    - https://github.com/kpu/kenlm/archive/master.zip
    - nltk
    - soundfile
    - youtube-dl
    - scipy
    - ffmpeg-python
    # - -r file:requirements.txt